server:
  port: 3214
  servlet:
    context-path: /Shop


spring:
  devtools:
    livereload:
      port: 35731
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: 51423
  jpa:
    properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQLDialect
       format_sql: true
       highlight_sql: true
    hibernate:
      ddl-auto: update
    show_sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: "783776844993-p48c7to68md26fvcru74hbo55a4vit9h.apps.googleusercontent.com"
            clientSecret: "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"
            redirectUri: "http://localhost:3214/Shop/login/oauth2/code/google"
            clientName: Google
            scope:
              - email
              - profile

          facebook:
            clientId: "767909744695077"
            clientSecret: "176e8d9076a4c69270fd683de7761e9a"
            redirectUri: "http://localhost:3214/Shop/login/oauth2/code/facebook"
            clientName: Google
            scope:
              - email
              - public_profile

logging:
  level:
    root: warn
#   file:
#     name: logs/Shop-backend.log
#   logback:
#     rollingpolicy:
#       file-name-pattern: logs/Shop-backend-%d{yyyy-MM-dd}.%i.log
#       max-file-size: 100KB
#       total-size-cap: 1MB
#       max-history: 14
#       clean-history-on-start: true
