server:
  port: 8080
  servlet:
    context-path: /ShopAdmin # default page


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: root
  jpa:
    properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQLDialect
       format_sql: true
       highlight_sql: true
    hibernate:
      ddl-auto: update
    show_sql: true